# Generated by Django 5.1.6 on 2025-02-07 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefreshToken",
            new_name="Token",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_token_42167e_idx",
            old_name="refresh_tok_token_6c248f_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_user_id_98d51a_idx",
            old_name="refresh_tok_user_id_79bd41_idx",
        ),
        migrations.AlterModelTable(
            name="token",
            table="token",
        ),
    ]
