# Generated by Django 5.1.6 on 2025-02-09 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="book_title_e39da6_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="book_author_f8bd7b_idx"),
        ),
    ]
